import { MantineProvider } from "@mantine/core";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, expect, it, vi } from "vitest";
import { LocalReflection } from "./LocalReflection";
import { api } from "../../api/client";
import type { ReflectionSession } from "../../sessionTypes";
vi.mock("../../api/client", () => ({ api: { listSessions: vi.fn(), getSession: vi.fn(), createSession: vi.fn(), appendMessage: vi.fn(), reply: vi.fn(), confirmReview: vi.fn(), continueSession: vi.fn(), saveReviewDraft: vi.fn() } }));
const now = "2026-09-11T15:00:00Z";
const initial: ReflectionSession = { id: "11111111-1111-4111-8111-111111111111", created_at: now, updated_at: now, status: "active", messages: [], drafts: [], current_draft_id: null, memory_revisions: [] };
const saved: ReflectionSession = { ...initial, messages: [{ id: "user-id", role: "user", content: "我对新计划有些犹豫", created_at: now }] };
const review: ReflectionSession = { ...saved, status: "review", messages: [...saved.messages, { id: "assistant-id", role: "assistant", content: "这是一个暂时的理解。", created_at: now }], drafts: [{ id: "draft-id", text: "AI 的暂定回顾", created_at: now, source_message_ids: ["user-id"] }], current_draft_id: "draft-id" };
beforeEach(() => {
  vi.clearAllMocks(); window.localStorage.clear(); window.history.replaceState(null, "", "#capture");
  vi.mocked(api.listSessions).mockResolvedValue([]);
  vi.mocked(api.createSession).mockResolvedValue(initial);
  vi.mocked(api.appendMessage).mockResolvedValue(saved);
  vi.mocked(api.reply).mockResolvedValue(review);
});
function mount() { const confirmed = vi.fn(); render(<MantineProvider><LocalReflection info={{ directory: "/tmp/memories", aiEnabled: true, provider: "OpenAI", model: "test" }} onConfirmed={confirmed}>{null}</LocalReflection></MantineProvider>); return confirmed; }
it("requires opt-in before AI; records locally first, then lets the user edit and confirm a draft", async () => {
  const done = mount(); const user = userEvent.setup();
  await user.type(screen.getByLabelText("此刻想说的话"), "我对新计划有些犹豫");
  await user.click(screen.getByRole("button", { name: "发送" }));
  expect(api.reply).not.toHaveBeenCalled();
  expect(api.appendMessage).not.toHaveBeenCalled();
  await user.click(await screen.findByRole("button", { name: "开启 AI 并发送" }));
  const editor = await screen.findByRole("textbox", { name: "回顾正文" });
  expect(screen.queryByLabelText("此刻想说的话")).not.toBeInTheDocument();
  expect(screen.getByRole("region", { name: "先聊到这里" })).toHaveFocus();
  expect(vi.mocked(api.appendMessage).mock.invocationCallOrder[0]).toBeLessThan(vi.mocked(api.reply).mock.invocationCallOrder[0]);
  expect(api.confirmReview).not.toHaveBeenCalled();
  await user.clear(editor); await user.type(editor, "我自己的回顾");
  vi.mocked(api.confirmReview).mockResolvedValue({ ...review, status: "completed", memory_revisions: [{ id: initial.id, user_id: "local", raw_input: "我自己的回顾", ai_summary: "我自己的回顾", created_at: now, updated_at: now }] });
  await user.click(screen.getByRole("button", { name: "确认并保存为记忆" }));
  await waitFor(() => expect(done).toHaveBeenCalledOnce());
  expect(api.confirmReview).toHaveBeenCalledWith(initial.id, "我自己的回顾", "draft-id");
  expect(await screen.findByText("这段回顾已由你确认，并保存在本机")).toBeInTheDocument();
});
it("can leave an unconfirmed review, saving edits locally without creating a memory", async () => {
  window.history.replaceState(null, "", `#capture?session=${review.id}`);
  vi.mocked(api.getSession).mockResolvedValue(review);
  vi.mocked(api.saveReviewDraft).mockResolvedValue({ ...review, current_draft_id: "edited-id", drafts: [...review.drafts, { id: "edited-id", text: "稍后再确认的理解", author: "user", created_at: now, source_message_ids: ["user-id"] }] });
  mount(); const user = userEvent.setup();
  const editor = await screen.findByRole("textbox", { name: "回顾正文" });
  await user.clear(editor); await user.type(editor, "稍后再确认的理解");
  await user.click(screen.getByRole("button", { name: "稍后再看" }));
  await screen.findByLabelText("此刻想说的话");
  expect(api.saveReviewDraft).toHaveBeenCalledWith(review.id, "稍后再确认的理解", "draft-id");
  expect(api.confirmReview).not.toHaveBeenCalled();
  expect(api.reply).not.toHaveBeenCalled();
  expect(window.location.hash).toBe("#capture");
});
it("only returns to the composer when the user chooses to continue, without sending another AI request", async () => {
  window.history.replaceState(null, "", `#capture?session=${review.id}`);
  vi.mocked(api.getSession).mockResolvedValue(review);
  vi.mocked(api.continueSession).mockResolvedValue({ ...review, status: "active", current_draft_id: null });
  mount(); const user = userEvent.setup();
  await screen.findByRole("textbox", { name: "回顾正文" });
  await user.click(screen.getByRole("button", { name: "继续聊" }));
  const input = await screen.findByLabelText("此刻想说的话");
  await waitFor(() => expect(input).toHaveFocus());
  expect(api.continueSession).toHaveBeenCalledWith(review.id);
  expect(api.reply).not.toHaveBeenCalled();
  expect(api.saveReviewDraft).not.toHaveBeenCalled();
  expect(screen.queryByRole("textbox", { name: "回顾正文" })).not.toBeInTheDocument();
});
it("keeps review edits on screen if saving for later fails", async () => {
  window.history.replaceState(null, "", `#capture?session=${review.id}`);
  vi.mocked(api.getSession).mockResolvedValue(review);
  vi.mocked(api.saveReviewDraft).mockRejectedValueOnce(new Error("本机暂时无法写入"));
  mount(); const user = userEvent.setup();
  const editor = await screen.findByRole("textbox", { name: "回顾正文" });
  await user.type(editor, "，还不确定");
  await user.click(screen.getByRole("button", { name: "稍后再看" }));
  expect(await screen.findByText("本机暂时无法写入")).toBeInTheDocument();
  expect(editor).toHaveValue("AI 的暂定回顾，还不确定");
  expect(window.location.hash).toContain(review.id);
  expect(api.confirmReview).not.toHaveBeenCalled();
});
it("keeps saved user text visible on AI failure and can retry without resending it", async () => {
  window.localStorage.setItem("pensieve.cloud-ai-consent.v1", "enabled");
  mount(); const user = userEvent.setup();
  vi.mocked(api.reply).mockRejectedValueOnce(new Error("AI 暂时未能回复"));
  await user.type(screen.getByLabelText("此刻想说的话"), "我对新计划有些犹豫");
  await user.click(screen.getByRole("button", { name: /^发送$/ }));
  expect(await screen.findByText("AI 暂时未能回复")).toBeInTheDocument();
  expect(screen.getByText("我对新计划有些犹豫")).toBeInTheDocument();
  await user.click(screen.getByRole("button", { name: "生成 / 重试 AI 回复" }));
  expect(await screen.findByRole("textbox", { name: "回顾正文" })).toHaveValue("AI 的暂定回顾");
  expect(api.appendMessage).toHaveBeenCalledOnce();
});

it("remembers a local-only choice and never calls AI on subsequent messages", async () => {
  mount(); const user = userEvent.setup();
  await user.type(screen.getByLabelText("此刻想说的话"), "合成原文");
  await user.click(screen.getByRole("button", { name: "发送" }));
  await user.click(await screen.findByRole("button", { name: "先只保存原文" }));
  await screen.findByText("已保存到本机");
  await user.type(screen.getByLabelText("此刻想说的话"), "合成后续");
  await user.click(screen.getByRole("button", { name: "保存" }));
  await waitFor(() => expect(api.appendMessage).toHaveBeenCalledTimes(2));
  expect(api.reply).not.toHaveBeenCalled();
  expect(window.localStorage.getItem("pensieve.cloud-ai-consent.v1")).toBe("disabled");
  await waitFor(() => expect(screen.queryByRole("dialog")).not.toBeInTheDocument());
});
it("opens a past chat from the dated history list", async () => {
  vi.mocked(api.listSessions).mockResolvedValue([{ id: review.id, title: "合成过去的聊天", status: "review", updated_at: now, message_count: 2 }]);
  vi.mocked(api.getSession).mockResolvedValue(review);
  const close = vi.fn();
  render(<MantineProvider><LocalReflection historyOpen onHistoryClose={close} info={null} onConfirmed={() => {}}>{null}</LocalReflection></MantineProvider>);
  const user = userEvent.setup();
  await user.click(await screen.findByRole("button", { name: /合成过去的聊天/ }));
  await waitFor(() => expect(close).toHaveBeenCalled());
  expect(api.getSession).toHaveBeenCalledWith(review.id);
  expect(window.location.hash).toContain(review.id);
});
